# 이메일 로그인
query EmailSignIn($email: String!, $password: String!) {
  emailSignIn(email: $email, password: $password) {
    success
    message
    token {
      access_token
      refresh_token
    }
  }
}

# 토큰 검증
query VerifyToken {
  verifyToken {
    success
    message
  }
}

# 토큰 갱신
query RefreshToken($token: TokenInput!) {
  refreshToken(token: $token) {
    success
    message
    token {
      access_token
      refresh_token
    }
  }
}
