query EmailSignIn($email: String!, $password: String!) {
  emailSignIn(email: $email, password: $password) {
    success
    message
    token {
      access_token
      refresh_token
    }
  }
}

query VerifyToken {
  verifyToken {
    success
    message
  }
}
