# 회원가입
mutation SignUp($input: SignUpInput!) {
  signUp(input: $input) {
    success
    message
  }
}

# 이메일로 사용자 조회
query FindUserByEmail($email: String) {
  findUserByEmail(email: $email) {
    success
    message
    user {
      email
      name
      type
      role
      lastLoginAt
      profileImage
      phoneNumber
      createdAt
      updatedAt
      point {
        point
        reason
        createdAt
        updatedAt
        pointHistory {
          point
          reason
          createdAt
          updatedAt
        }
      }
    }
  }
}

# 휴대폰 번호 수정
mutation SavePhoneNumber($phoneNumber: String!, $email: String) {
  savePhoneNumber(phoneNumber: $phoneNumber, email: $email) {
    success
    message
  }
}
