mutation SignUp($input: SignUpInput!) {
  signUp(input: $input) {
    success
    message
  }
}

query VerifyPassword($email: String!, $password: String!) {
  verifyPassword(email: $email, password: $password) {
    success
    message
  }
}

query FindUserByEmail {
  findUserByEmail {
    success
    message
    user {
      email
      name
      type
      role
      lastLoginAt
      profileImage
      phoneNumber
      createdAt
      updatedAt
    }
  }
}

query CheckAdminUser {
  checkAdminUser {
    success
    message
  }
}
